// ─── Agent definitions ───
//
// Rax used to ship with free-form tabs (user could spawn N claude sessions and
// rename them). The multi-agent model replaces that with a fixed roster: five
// named "agents", each bound to one persistent claude session. Tabs ARE
// agents now; there is no add/remove.
//
// The dock window (see src/renderer/dock) renders these five identities as a
// vertical glass dock parked on the left edge of the user's primary display.
// Selecting an agent in the dock routes focus to that agent's tab in pill /
// fullscreen. The voice orb on its own surface coordinates the roster — it
// can dispatch a turn to a specific agent, and emits a completion toast when
// that agent's run finishes.

export interface AgentDefinition {
  /** Stable tab id used across renderer / main / persisted state. Reserved
   *  string — never collide with a real claude tab id generated by main. */
  id: string
  /** Display name shown in the dock tooltip, sidebar row, and toasts. */
  name: string
  /** One-line tagline displayed under the name on hover. Pure flavor. */
  tagline: string
  /** Theme accent for status pulses, hover halo, active indicator pill.
   *  Both light and dark modes pick the same hex — the dock surface is
   *  always dark-glass so contrast holds. */
  accent: string
  /** Soft accent variant used for status backgrounds and glow shadows. */
  accentSoft: string
  /** Single character/emoji rendered as the agent's icon glyph in the
   *  dock and sidebar. Cheap, scales perfectly, no extra asset pipeline.
   *  Pick visually distinct shapes so the roster is recognizable at the
   *  60×60 dock size. */
  glyph: string
}

/** The fixed roster. Five agents, ordered top-to-bottom in the dock. */
export const AGENTS: readonly AgentDefinition[] = [
  {
    id: 'agent-max',
    name: 'Max',
    tagline: 'the heavy lifter',
    accent: '#34d5d8',
    accentSoft: 'rgba(52, 213, 216, 0.18)',
    glyph: 'M',
  },
  {
    id: 'agent-alex',
    name: 'Alex',
    tagline: 'the architect',
    accent: '#7aa7ff',
    accentSoft: 'rgba(122, 167, 255, 0.18)',
    glyph: 'A',
  },
  {
    id: 'agent-luna',
    name: 'Luna',
    tagline: 'the night owl',
    accent: '#b388ff',
    accentSoft: 'rgba(179, 136, 255, 0.18)',
    glyph: 'L',
  },
  {
    id: 'agent-nova',
    name: 'Nova',
    tagline: 'the spark',
    accent: '#5dd5a8',
    accentSoft: 'rgba(93, 213, 168, 0.18)',
    glyph: 'N',
  },
  {
    id: 'agent-zara',
    name: 'Zara',
    tagline: 'the closer',
    accent: '#ff6b9d',
    accentSoft: 'rgba(255, 107, 157, 0.18)',
    glyph: 'Z',
  },
] as const

/** Quick lookup by id. Built once at module load. */
const AGENT_BY_ID: Map<string, AgentDefinition> = new Map(AGENTS.map((a) => [a.id, a]))

export function getAgent(id: string): AgentDefinition | undefined {
  return AGENT_BY_ID.get(id)
}

export function isAgentId(id: string | undefined | null): boolean {
  return !!id && AGENT_BY_ID.has(id)
}

/** Stable id for the default agent the app boots into. */
export const DEFAULT_AGENT_ID = AGENTS[0].id
